name = "logical-mechanism/Seedelf-Wallet"
version = "0.1.2"
compiler = "v1.1.7"
plutus = "v3"
license = "GPL-3.0-or-later"
description = "A Cardano Stealth Wallet"

[repository]
user = "logical-mechanism"
project = "Seedelf-Wallet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]