name = "logicalmechanism/5eed0e1f"
version = "0.0.1"
license = "GPL-3.0"
description = "Aiken contracts for project 'logicalmechanism/5eed0e1f'"

[repository]
user = "logicalmechanism"
project = "5eed0e1f"
platform = "github"

[[dependencies]]
name = "logicalmechanism/stdlib"
version = "plutus-v3"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "plutus-v3"
source = "github"
