name = "logicalmechanism/5eed0e1f"
version = "1.0.0"
compiler = "v1.1.0"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'logicalmechanism/5eed0e1f'"

[repository]
user = "logicalmechanism"
project = "5eed0e1f"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "candidate-for-v0.5.0"
source = "github"

[config]