name = "logicalmechanism/5eed0e1f"
version = "0.0.0"
compiler = "v1.0.31-alpha"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'logicalmechanism/5eed0e1f'"

[repository]
user = "logicalmechanism"
project = "5eed0e1f"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "plutus-v3"
source = "github"

[config]