#
# Network Information
network: "--testnet-magic 1"
#
# Contract Addresses
wallet_address: "addr_test1wpk2edu6248lqm3ecas82auzyvpsvs7vzv3tqtjvujtnxds9v3s2s"
#
# Address Holding Script References UTxOs
reference_address: "addr_test1wzu7drmul6s5g2w3v90kjywl9dd5vy34rhud0nr2f2zktvqc9k7h8"
#
# wallet and seedelf Contract Script Reference UTxOs
wallet_ref_utxo: "6eb57b9de84eea4b5db704b1fa089d5b98d64e61b012a5d7aee4a9b97c1b7b82#1"
wallet_lovelace: 3969510
#
seedelf_ref_utxo: "784b80854a79b00f48ace0138590edd1a65264760cebc781478a8f71102ec26f#1"
seedelf_lovelace: 3659190
#
# The Seedelf Policy Id
seedelf_policy: "0e1ceea59a67ece12e067c747a3b8c900c0122beb93fc300f14f5a8b"
#
# Starting Block Information
starting_block_number: 2834390
starting_timestamp: 74560053
starting_blockhash: "4e201fabc813f32668fbb649cbee887bdcbee6242bae6603d660b67a4df68c7a"
delay_depth: 3
#
# Logging Parameters
max_log_file_size: "5 MB"
max_num_log_files: 1
#
# Available logging levels
#
# Options: DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
logging_level: "DEBUG"
