[source]
type = "N2N"
address = [ "Tcp", "preprod-node.play.dev.cardano.org:3001",]
magic = "preprod"
min_depth = 3

[sink]
type = "Webhook"
url = "http://localhost:44203/webhook"
timeout = 60000
error_policy = "Continue"

[source.intersect]
type = "Point"
value = [ 74747445, "bd084d7e7248bbce864a7966e1194b314852d5b83202c701aae2894921703846",]

[source.mapper]
include_block_end_events = true
include_transaction_details = true

[sink.retry_policy]
max_retries = 60
backoff_unit = 20000
backoff_factor = 2
max_backoff = 100000
