[source]
type = "N2N"
address = [ "Tcp", "preprod-node.play.dev.cardano.org:3001",]
magic = "preprod"
min_depth = 3

[sink]
type = "Webhook"
url = "http://localhost:44203/webhook"
timeout = 60000
error_policy = "Continue"

[source.intersect]
type = "Point"
value = [ 74567104, "70c0956989dfdfdf8231fb9ccc945add1bce6599a638893272cb45e1c66b16dc",]

[source.mapper]
include_block_end_events = true
include_transaction_details = true

[sink.retry_policy]
max_retries = 60
backoff_unit = 20000
backoff_factor = 2
max_backoff = 100000
