name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.9
      - run: aiken fmt --check
        working-directory: seedelf-cli
      - run: aiken check -D
        working-directory: seedelf-cli
      - run: aiken build
        working-directory: seedelf-cli