name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (Linux)
        working-directory: seedelf-cli
        run: cargo build --release

      - name: Move Binary (Linux)
        working-directory: seedelf-cli
        run: mv target/release/seedelf-cli seedelf-cli

      - name: Generate Checksum (Linux)
        working-directory: seedelf-cli
        run: sha256sum seedelf-cli > seedelf-cli.sha256

      - name: Compress Binary and Checksum (Linux)
        working-directory: seedelf-cli
        run: tar -czvf seedelf-cli-linux.tar.gz seedelf-cli seedelf-cli.sha256

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: seedelf-cli-linux
          path: seedelf-cli/seedelf-cli-linux.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build (Windows)
        working-directory: seedelf-cli
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Move Binary (Windows)
        shell: pwsh
        working-directory: seedelf-cli
        run: mv target\x86_64-pc-windows-gnu\release\seedelf-cli.exe seedelf-cli.exe

      - name: Generate Checksum (Windows)
        shell: pwsh
        working-directory: seedelf-cli
        run: |
          $hash = Get-FileHash seedelf-cli.exe -Algorithm SHA256
          $hash.Hash | Out-File -Encoding ASCII seedelf-cli.sha256

      - name: Compress Binary and Checksum (Windows)
        shell: pwsh
        working-directory: seedelf-cli
        run: Compress-Archive -Path seedelf-cli.exe,seedelf-cli.sha256 -DestinationPath seedelf-cli-windows.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: seedelf-cli-windows
          path: seedelf-cli/seedelf-cli-windows.zip

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install x86_64-apple-darwin Target
        run: rustup target add x86_64-apple-darwin

      - name: Build (macOS)
        working-directory: seedelf-cli
        run: cargo build --release --target x86_64-apple-darwin

      - name: Move Binary (macOS)
        working-directory: seedelf-cli
        run: mv target/x86_64-apple-darwin/release/seedelf-cli seedelf-cli

      - name: Generate Checksum (macOS)
        working-directory: seedelf-cli
        run: shasum -a 256 seedelf-cli > seedelf-cli.sha256

      - name: Compress Binary and Checksum (macOS)
        working-directory: seedelf-cli
        run: tar -czvf seedelf-cli-macos.tar.gz seedelf-cli seedelf-cli.sha256

      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: seedelf-cli-macos
          path: seedelf-cli/seedelf-cli-macos.tar.gz

  finalize-release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-windows
      - build-mac
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: seedelf-cli-linux
          path: seedelf-cli-linux.tar.gz

      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: seedelf-cli-windows
          path: seedelf-cli-windows.zip

      - name: Download MacOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: seedelf-cli-macos
          path: seedelf-cli-macos.tar.gz


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          body: |
            ### New Release: ${{ github.ref_name }}

            This release includes:
            - Binaries and checksums for Linux, Windows, and macOS.

            Thank you for using `seedelf-cli`.

            If you encounter any issues, please report them [here](https://github.com/logical-mechanism/Seedelf-Wallet/issues).
          generate_release_notes: true
          files: |
            seedelf-cli-linux.tar.gz
            seedelf-cli-windows.zip
            seedelf-cli-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
