[package]
name = "seedelf-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
dirs = "5.0"
whoami = "1.5.2"
blstrs = "0.7.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_cbor = "0.11.2"
hex = "0.4.3"
rand_core = { version = "0.6.4", features = ["std"] }
ff = "0.13.0"
blake2 = "0.10.6"
tokio = { version = "1.41.1", features = ["full"] }
reqwest = { version = "0.12.9", features = ["json"] }
pallas-addresses = "0.31.0"
pallas-crypto = "0.31.0"
pallas-codec = "0.31.0"
pallas-txbuilder = "0.31.0"
pallas-traverse = "0.31.0"
pallas-wallet = "0.31.0"
pallas-primitives = "0.31.0"
warp = "0.3.7"